fix: original image with size
TylerBarnes/gatsby-wordpress-inline-images pull request #20
Opened 2019-10-24 21:38 UTC by rgllm

@riencoertjens this fixes the issue discussed here https://github.com/TylerBarnes/gatsby-wordpress-inline-images/issues/15.

Please let me know if you have any question.

2019-10-31 22:31 UTC, TylerBarnes commented on src/gatsby-node.js
> +  try{
Thanks so much for this! It looks great. Would you mind adding a couple comments as to why we have to do this and what the second download is for?
I can also add them if you'd like, just don't want to mess with your PR :) Let me know

2019-10-31 22:31 UTC, TylerBarnes requested changes
Thanks so much for this! It looks great. Would you mind adding a couple comments as to why we have to do this and what the second download is for?
I can also add them if you'd like, just don't want to mess with your PR :) Let me know

2019-11-01 12:51 UTC, rgllm commented
> Thanks so much for this! It looks great. Would you mind adding a couple comments as to why we have to do this and what the second download is for?
> I can also add them if you'd like, just don't want to mess with your PR :) Let me know

Done @TylerBarnes 👍

2019-11-27 00:08 UTC, rgllm commented
@TylerBarnes any updates on this?

2019-12-04 01:40 UTC, merged

2019-12-04 02:30 UTC, TylerBarnes commented
@rgllm apologies for the delay on this. I was on vacation and then was working super hard writing the new version of `gatsby-source-wordpress`! I joined the Gatsby core team recently. Heads up, when `gatsby-source-wordpress@v4` drops, this package will be deprecated. See https://github.com/gatsbyjs/gatsby/issues/19292 for more info

2019-12-04 02:30 UTC, TylerBarnes commented
Also, this is published in `gatsby-wordpress-inline-images@1.1.0`! Thanks again!

2019-12-04 12:24 UTC, rgllm commented
> @rgllm apologies for the delay on this. I was on vacation and then was working super hard writing the new version of `gatsby-source-wordpress`! I joined the Gatsby core team recently. Heads up, when `gatsby-source-wordpress@v4` drops, this package will be deprecated. See [gatsbyjs/gatsby#19292](https://github.com/gatsbyjs/gatsby/issues/19292) for more info

I've been following your work with v4 @TylerBarnes. Good job there, would love to talk with you about that 👍

2019-12-04 17:47 UTC, TylerBarnes commented
@rgllm and I'd love to hear your thoughts! Feel free to dm me on twitter (@tylbar) or comment in the epic :) Hopefully soon I'll have an experimental release ready for people to try out